version: '3.8'

services:
  app:
    build: .
    container_name: funding_pips_app
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:password@db:5432/fundingpips
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fundingpips
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - app
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
